# Generated by Django 4.1.5 on 2023-02-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_initial'),
        ('store', '0001_initial'),
        ('customer', '0003_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_channels',
            field=models.ManyToManyField(related_name='+', to='store.saleschannel'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='product.producttag'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.producttype'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='customer_groups',
            field=models.ManyToManyField(related_name='+', to='customer.customergroup'),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payment.currency'),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.pricelist'),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.region'),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('sku', 'barcode', 'ean', 'upc')},
        ),
    ]
