# Generated by Django 4.1.5 on 2023-01-30 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttaxrate',
            name='rate_id',
        ),
        migrations.AddField(
            model_name='discountcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discountcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='discountconditionproducttag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discountconditionproducttag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitemadjustment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitemadjustment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitemtaxline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitemtaxline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='moneyamount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='oauth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oauth',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitemchange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitemchange',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='producttaxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producttaxrate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='producttaxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='producttypetaxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producttypetaxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantinventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantinventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='publishableapikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publishableapikey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='publishableapikeysaleschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='publishableapikeysaleschannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='returnreason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='saleschannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='saleschannellocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='saleschannellocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethodtaxline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethodtaxline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingoption',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingoption',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingoptionrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingoptionrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingtaxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingtaxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stagedjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stagedjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='swap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trackinglink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analyticsconfig',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchjob',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimimage',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='claimtag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customshippingoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountcondition',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountconditioncustomergroup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountconditionproduct',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountconditionproductcollection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountconditionproducttag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountconditionproducttype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='draftorder',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fulfillmentitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fulfillmentprovider',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineitemadjustment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineitemtaxline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moneyamount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notificationprovider',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oauth',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedit',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordergiftcard',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderitemchange',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcollection',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttypetaxrate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productvariantinventoryitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishableapikey',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publishableapikeysaleschannel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refund',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='return',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='returnreason',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleschannel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='saleschannellocation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingmethodtaxline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingoptionrequirement',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shippingtaxrate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stagedjob',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='swap',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxprovider',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc5504bc-a698-4b72-babb-d70000df895a'), primary_key=True, serialize=False),
        ),
    ]
