"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 2.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

import environ


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR =  os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

# setup the enviroment

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
env = environ.Env(SITE_ID=int, BROKER_URL=str, USE_S3=bool)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "#*!9s)4s)(vulr!5bmj(0z=jjk4im#l1_my3q@ku)09qd_dl$@"

RATE_LIMIT_MUTATION = env('RATE_LIMIT_MUTATION')
CLOUD_FLARE_KEY = env('CLOUD_FLARE_KEY')
CLOUD_FLARE_ZONEID = env('CLOUD_FLARE_ZONEID')

# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    "solo",
    'social_django',
    "django_extensions",
    "graphene_django",
    "channels",
    "djcelery_email",
    "secure_auth",
    "secret",
    "subscription",
    "slackextension"
]

MIDDLEWARE = [
    "core.middlewares.ratelimit_middleware.ParseClientIpMiddleware",
    "multitenant.middleware.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
   
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "secureconsole.urls"


WSGI_APPLICATION = "secureconsole.wsgi.application"
ASGI_APPLICATION = "secureconsole.asgi.application"


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


SITE_ID = 1
