# Generated by Django 4.1.7 on 2023-03-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='region',
        ),
    ]
