# Generated by Django 4.1.7 on 2023-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0020_cart_created_by_cart_updated_by_invite_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("danger", "Danger"),
                    ("success", "Success"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
