# Generated by Django 4.1.7 on 2023-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0026_alter_notification_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("warning", "Warning"),
                    ("danger", "Danger"),
                    ("success", "Success"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
