# Generated by Django 4.1.6 on 2023-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
