# Generated by Django 4.1.7 on 2023-03-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='region',
            name='tax_rate',
        ),
    ]
