# Generated by Django 4.1.7 on 2023-03-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customer_groups_remove_customer_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='metadata',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Email of the customer, must be unique.', max_length=254, unique=True),
        ),
    ]
