# Generated by Django 4.1.7 on 2023-03-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0006_alter_address_country_alter_address_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customergroup",
            name="price_lists",
        ),
        migrations.AlterField(
            model_name="customer",
            name="billing_address",
            field=models.OneToOneField(
                blank=True,
                help_text="Billing address of the customer, not required.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="customer.address",
            ),
        ),
    ]
