# Generated by Django 4.1.7 on 2023-03-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_remove_customergroup_price_lists_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customergroup",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
