# Generated by Django 4.1.7 on 2023-03-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_initial"),
        ("tax", "0002_remove_taxrate_metadata_remove_taxrate_region"),
        ("customer", "0008_alter_customergroup_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="metadata",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="payment.currency",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="tax_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tax.taxprovider",
            ),
        ),
    ]
