# Generated by Django 4.1.7 on 2023-03-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('customer', '0010_alter_address_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.currency'),
        ),
    ]
