# Generated by Django 4.1.7 on 2023-03-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
        ('customer', '0011_alter_region_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payment.currency'),
            preserve_default=False,
        ),
    ]
