# Generated by Django 4.1.7 on 2023-04-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_initial"),
        ("customer", "0012_alter_region_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="payment.currency",
            ),
        ),
    ]
