# Generated by Django 4.1.5 on 2023-02-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='shipping_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.shippingmethod'),
        ),
    ]
