# Generated by Django 4.1.7 on 2023-03-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_initial"),
        ("product", "0004_remove_productcollection_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="shipping.shippingprofile",
            ),
        ),
    ]
