# Generated by Django 4.1.7 on 2023-03-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_notification_level"),
        ("product", "0006_alter_product_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="product.image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_channels",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="store.saleschannel"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="product.producttag"
            ),
        ),
    ]
