# Generated by Django 4.1.7 on 2023-03-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0016_alter_notification_level"),
        ("product", "0007_alter_product_images_alter_product_sales_channels_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricelist",
            name="customer_groups",
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(related_name="+", to="product.image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_channels",
            field=models.ManyToManyField(related_name="+", to="store.saleschannel"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(related_name="+", to="product.producttag"),
        ),
    ]
