# Generated by Django 4.1.7 on 2023-04-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0013_alter_region_currency"),
        ("product", "0008_remove_pricelist_customer_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariant",
            old_name="allow_backorder",
            new_name="allow_back_order",
        ),
        migrations.AddField(
            model_name="pricelist",
            name="customer_groups",
            field=models.ManyToManyField(related_name="+", to="customer.customergroup"),
        ),
    ]
