# Generated by Django 4.1.7 on 2023-07-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_image_created_by_image_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="each_unit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_expirable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_count_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
