# Generated by Django 4.1.7 on 2023-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_product_each_unit_count_product_is_expirable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="length",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
        migrations.RemoveField(
            model_name="product",
            name="width",
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="Product/Thumbnail"
            ),
        ),
    ]
