# Generated by Django 4.1.7 on 2023-08-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_remove_product_height_remove_product_length_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="length",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
