# Generated by Django 4.1.7 on 2023-08-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0014_address_created_by_address_updated_by_and_more"),
        ("product", "0014_remove_product_origin_country_image_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="origin_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.country",
            ),
        ),
    ]
