# Generated by Django 4.1.7 on 2023-08-07 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_remove_image_url_remove_producttaxrate_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.producttypetaxrate",
            ),
        ),
    ]
