# Generated by Django 4.1.7 on 2023-08-07 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_productvariant_product_productvariant_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcollection",
            name="products",
        ),
    ]
