# Generated by Django 4.1.7 on 2023-08-12 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_remove_productcollection_products"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="type",
            new_name="product_type",
        ),
    ]
