# Generated by Django 4.1.7 on 2023-08-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_rename_type_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("New", "New"),
                    ("Used", "Used"),
                    ("Refurbished", "Refurbished"),
                ],
                default="New",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="+", to="product.image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "DRAFT"),
                    ("proposed", "PROPOSED"),
                    ("published", "PUBLISHED"),
                    ("rejected", "REJECTED"),
                ],
                default="draft",
                max_length=255,
                null=True,
            ),
        ),
    ]
